### ISSUE TITLE
error: "Running setfiles on install tree failed: [Errno 2] No such file or dir: 'setfiles': 'setfiles'**"

### ISSUE THREAD

**Issue by hjimmy** [AlmaLinux/docker-images#3]
$ sh build.sh
.....
2021-02-24 19:22:58,436: Error in atexit._run_exitfuncs:
2021-02-24 19:22:58,437: Traceback (most recent call last):
2021-02-24 19:22:58,437: File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
2021-02-24 19:22:58,437: return self._handle_method_error(error)
2021-02-24 19:22:58,437: File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
2021-02-24 19:22:58,437: raise exception from None
2021-02-24 19:22:58,437: dasbus.error.DBusError: umount of /mnt/sysimage/run failed (32)
**2021-02-24 19:22:58,617: Running setfiles on install tree failed: [Errno 2] No such file or dir: 'setfiles': 'setfiles'**
2021-02-24 19:26:46,610: Disk Image install successful
2021-02-24 19:26:46,625: SUMMARY
2021-02-24 19:26:46,625: -------
2021-02-24 19:26:46,627: Logs are in /root/docker-images
2021-02-24 19:26:46,629: Disk image is at /root/docker-images/result/almalinux-8-docker.tar.xz
2021-02-24 19:26:46,629: Results are in /root/docker-images/result

**Comment by srbala** [comment]
@hjimmy at this point script is not failing due this error, continue with process after the error outputs the tar file. Do you see any problem in output file due this error?

**Comment by srbala** [comment]
@hjimmy I am closing this issue. We can reopen if found more details or impact on output
