### ISSUE TITLE
Build error : ./build.sh -t base -v 9

### ISSUE THREAD

**Issue by perry-amsterdam** [AlmaLinux/docker-images#59]
Hi, i get the following build error:

./build.sh -t base -v 9

2022-05-10 22:34:10,299: ...
2022-05-10 22:34:10,300: Configuring installed system
2022-05-10 22:34:13,462: ...................
2022-05-10 22:34:13,463: Creating users
2022-05-10 22:34:13,463: Configuring addons
2022-05-10 22:34:13,476: ..
2022-05-10 22:34:13,477: Generating initramfs
2022-05-10 22:34:13,955: ...
2022-05-10 22:34:13,956: Running post-installation scripts
2022-05-10 22:34:13,958: .
2022-05-10 22:34:13,958: Installation complete
2022-05-10 22:34:13,958: 
2022-05-10 22:34:13,958: Use of this product is subject to the license agreement found at:
2022-05-10 22:34:13,958: /usr/share/redhat-release/EULA
2022-05-10 22:34:13,959: 
2022-05-10 22:34:15,048: Error in atexit._run_exitfuncs:
2022-05-10 22:34:15,049: Traceback (most recent call last):
2022-05-10 22:34:15,049: File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
2022-05-10 22:34:15,049: return self._handle_method_error(error)
2022-05-10 22:34:15,049: File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
2022-05-10 22:34:15,049: raise exception from None
2022-05-10 22:34:15,050: dasbus.error.DBusError: umount of /mnt/sysimage/run failed (32)
2022-05-10 22:34:15,292: Running setfiles on install tree failed: [Errno 2] No such file or directory: 'setfiles': 'setfiles'
2022-05-10 22:34:15,292: Shutting down log processing
2022-05-10 22:36:21,074: Disk Image install successful
2022-05-10 22:36:21,076: SUMMARY
2022-05-10 22:36:21,076: -------
2022-05-10 22:36:21,076: Logs are in /root/docker-images
2022-05-10 22:36:21,077: Disk image is at /root/docker-images/result_x86_64_9_x86_64-base/almalinux-9-docker-x86_64-base.tar.xz
2022-05-10 22:36:21,077: Results are in /root/docker-images/result_x86_64_9_x86_64-base

**Comment by srbala** [comment]
@perry-amsterdam this is documented known issue https://github.com/AlmaLinux/docker-images#known-issues process will still produce an output file, as shown in your log at the end.
